### ISSUE TITLE
Ground rule

### ISSUE THREAD

**Issue by simsulison** [WinterSpringProject/PROJECT-GLFP#1]
# Ground rule
Project ground rule을 정해봅시다.

**Comment by k0k0k02** [comment]
* Ground rule을 정할 때 4명이 5가지 정도씩 의견내는건 어떨까요?
* 주 1회 정도 정기적인 회의 시간을 정해 그 시간을 미리 비워둘 수 있으면 좋을 것 같습니다!

1. 참가자들은 자유롭게 의견을 제시하며, 건설적인 관점에서 의견을 피드백한다.
2. 프로젝트의 개발 및 실력향상을 위해 성실히 임한다.
3. 궁금하거나 이해되지 않는 것이 있으면 질문한다.
4. 논의의 주제에서 벗어나면 누구라도 신호를 보낸다.
5. 약속된 시간을 엄수한다.
6. 팀플레이를 한다.

**Comment by simsulison** [comment]
1. 다른 사람의 아이디어를 깎아 내리지 않는다.
2. 워크숍이 성공적으로 마무리 되는데 공동의 책임을 진다.
3. 열정적으로 참석한다.
4. 비판적이기 보다 발전적인 관점에서 논의한다.

**Comment by Jin-s-work** [comment]
1. 다른 사람의 관점이나 의견에 대해서 감사한다.
2. 소통하고 소통하고 소통한다.
3. 나의 경험과 지식을 다른 사람과 공유한다.
4. 모든 사람이 대화에 참여할 수 있도록 배려하고 동기부여 한다.
5. 워크숍 진행이 좀 더 효과적일 수 있는 방법을 생각한다.

**Comment by bluewink** [comment]
1. 시간을 엄수한다.
2. 명확하지 않을 때는 질문한다.
3. 하나의 주제에 대해서 결과가 도출되고 모든 참가자가 동의한 후에 다음 주제에 대해서 논의한다
4. 모든 사람이 대화에 참여할 수 있도록 배려하고 동기부여한다.
5. 나의 경험과 지식을 다른 사람과 공유한다

**Comment by Ohhong** [comment]
그라운드 룰을 정할 때 해당 내용 이외에 convention도 맞춰주세요~
- issue를 생성 할 때의 양식
- commit 양식
- label 사용
- 기타 컨벤션

**Comment by simsulison** [comment]
- Issue 생성 할 때의 양식 : 제목은 영문으로 작성하고, 제목은 해당 issue 주제에 대한 명확한 내용을 담아야 합니다. (이 외 추가해야할 사안 있으면 comment로 추가 부탁드립니다.) 
- commit 양식 : Issue의 번호를 따라 Commit하는 것을 원칙으로 합니다. (ex. Issue#1 - 내용)  -> 해당 사안은 논의가 필요.
- label 사용 : label은 Issue 주제에 알맞는 label을 선택하고, 필요한 label이 있으면 팀원들에게 상의하여 추가하는 방향으로 사용한다.
- 기타 컨벤션 : 변수 선언은 항상 Camel Case를 따르기로 하고, Class 선언은 Pascal Case를 따르는 것을 원칙으로 합니다. (추가 사항 논의 필요)

위 내용에 대해서 추가하거나 수정해야 할 부분이 있으면 자유롭게 의견 내주세요.
