### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by bluewink** [WinterSpringProject/PROJECT-GLFP#11]
### Member
|Description|Method|URL|Request|Response|
|------------|--------|---------------|------|------------|
|조회|GET|/member/{member_id}||MemberDTO
|등록|POST|/member|MemberDTO|ResponseEntity: String
|수정|PUT|/member|MemberDTO|ResponseEntity: String
|삭제|DELETE|/member/{member_id}||ResponseEntity: String

### Board
|Description|Method|URL|Request|Response|
|------------|------------|---------------|-------------|---------------|
|전체 조회|GET|/board/{board_id}||List: BoardDTO|
|조회|GET|/board/post/{post_id}||BoardDTO|
|등록|POST|/board/post|BoardDTO|ResponseEntity: String
|수정|PUT|/board/post/{post_id}|BoardDTO|ResponseEntity: Long
|삭제|DELETE|/board/post/{post_id}||ResponseEntity: Long

**Comment by simsulison** [comment]
https://github.com/WinterSpringProject/PROJECT-GLFP/wiki/API_design
