### ISSUE TITLE
Technique Stack

### ISSUE THREAD

**Issue by simsulison** [WinterSpringProject/PROJECT-GLFP#2]
# 기술 스택 정하기

- JAVA 15
- Spring Boot 2.4.2
- Spring Data JPA
- MariaDB 10.5.8(stable)
- Junit5
- Node.js / Socket.io(Client side)
- Github

**Comment by simsulison** [comment]
- JAVA -> Version 논의
- Spring Boot -> Version 논의
- Spring Data JPA
- DB 선택해야 함.(프로젝트의 목적에 따라서 적절한 DB 선택)
- Junit5(Test code 작성 시)
- client side 기술스택 논의
- Github

**Comment by k0k0k02** [comment]
게시판 구현시
JAVA version 15
Spring Boot 2.4.2 사용하였으며, 버젼은 통일만 시키면 되어보입니다.

DB 관련 이슈
1. 관계형 DB / 비관계형 DB 선택
2. 1번 선택 시 구체적으로 어떤 DB를 사용할 것인지?

1) 일단 저희 프로젝트에서 다루는 데이터가 회원 관리 정도로 방대하거나 복잡한 구조를 가지고 있지 않다고 생각됩니다.
따라서 비교적 구조가 익숙하고 잘 유포되어 있는(웹 서치로 구현하기 편한) 관계형 DB를 사용하는 것이 좋아보입니다.

2) 관계형 DB 중 널리 알려져있고 무료로 사용가능한 Mysql, PostgreSql 정도의 선택지가 있는데, 앞서 언급했듯이 복잡한 구조를 갖고 있지 않기 때문에 비교적 간단한 작업에 이용하기 편한 Mysql을 사용하는 것이 적합해보입니다.

다른 의견이 있으시면 말씀해주세요!

**Comment by simsulison** [comment]
추가적으로 F.E side에서 필요한 기술스택 정리해서 알려주시고, DB는 제 생각에도 우선 MySQL로 진행하였다가, 새로운 기능을 추가하는 과정에서 다른 형태의 DB가 필요하다면 그 때 다시 논의 하여 교체해도 상관없다고 생각합니다.(Spring Data JPA를 사용하기 때문에 DB 교체 작업은 어렵지 않을 것이라고 생각합니다.) 

JAVA나 Spring boot 버전의 경우에는 수형님이 말씀하신대로 최신 버전을 사용하면 될 것 같습니다. 
해당 사안에 대해서 수정하여 올리겠습니다.

**Comment by k0k0k02** [comment]
client side 기술 스택 이슈

채팅 서버 개발에 대해 웹 서치를 한 결과 vue.js + socket.io를 사용하는 방법, node.js + vscode를 사용하는 방법 등 다양한 방법이 있었습니다. 채팅 서버 관련된 경험이 처음이므로 기술적인 부분의 비교보다 입문자도 따라가기 좋은 사이트를 쫓아가는 방식으로 시작하는 것이 좋다고 생각됩니다!

https://geundung.dev/58?category=719250
챗 서버 생성에 대해 안내되어 있는 블로그들을 여러개 찾아보았는데, 클라이언트를 웹으로 진행하면서 비교적 가장 잘 정리되어 있다고 생각되는 블로그입니다. 해당 블로그에서는 Node.js, VSCode를 사용하였습니다. 더 좋은 블로그를 찾게되면 새로 comment하겠습니다. 

Node.js : 챗 서버 생성을 위한 javascript엔진
VSCode: 텍스트 에디터

https://dahye-jeong.gitbook.io/til/nodejs/chapter10#10-4
위는 Socket.io를 사용하는 블로그입니다. 채팅 웹서버를 예쁘게 꾸미는 기능도 설명되어 있고, 그룹채팅 기능도 설명되어 있습니다. 둘 중 괜찮아 보이는 블로그 선택해주시면 될 것 같습니다!

다른 의견이 있으시거나, 기술적인 부분에 대한 선택이 필요하다고 생각하시면 comment 부탁드립니다!

**Comment by bluewink** [comment]
- DB 관련해서, 관계형 DB를 사용하는 것에 찬성합니다! JPA와 호환성이 뛰어날 것 같습니다.
다만, Mysql을 이야기하셨는데 mariaDB를 사용해보는 것도 좋을 것 같습니다! Mysql의 기능을 모두 제공하고, Mysql보다 가볍고 빠르다고 합니다. 그리고 라이센스 문제에서도 자유롭다고 하네요!
https://dtaxi.tistory.com/964

- F.E 기술 스택은 상우님이 사용하실 기술을 말씀하시는 건가요??

**Comment by simsulison** [comment]
- 그렇다면 DB의 경우에는 MariaDB를 사용하는 것이 좋다고 생각합니다. 해당 의견을 토대로 기술 스택 update하겠습니다. 
- F.E 기술 스택은 상우님이 사용하실 기술을 적기 위해서 추가해두었던 부분인데, repository가 나눠져 있으므로 이 repository에는 B.E 기술 스택만 작성하면 될 것 같습니다. 이 또한 update 하겠습니다.
