### ISSUE TITLE
Create AWS EC2 instance for DB

### ISSUE THREAD

**Issue by simsulison** [WinterSpringProject/PROJECT-GLFP#20]
mariaDB를 local 환경이 아닌 shared한 환경에서 사용하기 위해 AWS EC2 인스턴스를 생성하여 DB 서버를 올린다.

# Reference
- https://docs.aws.amazon.com/ko_kr/AmazonRDS/latest/UserGuide/CHAP_GettingStarted.CreatingConnecting.MariaDB.html
- https://velog.io/@ckstn0777/AWS-EC2-DB-%EA%B5%AC%EC%B6%95MariaDB

**Comment by simsulison** [comment]
Amazon에서 mySQL이나 mariaDB에 대해 쉽게 다룰 수 있도록 amazon RDS라는 기능을 제공하는데, 이는 비용이 많이 청구될 수 있으므로 AWS EC2 instance를 직접 생성하여 서버를 설치하기로 하였습니다.

**Comment by bluewink** [comment]
ec2 instance에 mariadb 설치, db 생성, user 권한 설정까지 마쳤습니다.
```
spring.datasource.username=[username]
spring.datasource.password=[password]
spring.datasource.url=jdbc:mariadb://3.15.215.122:3306/glfp
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
```


application.properties에 위와 같이 설정하면 됩니다.
|개발자|username|password|
|------|---|---|
|상빈|sb|sb|
|의석|es|es|
|수형|sh|sh|



## Example
```
spring.datasource.username=sb
spring.datasource.password=sb
```

## Notice
HeidiSQL 을 통한 외부 접속도 가능합니다.


![image](https://user-images.githubusercontent.com/59544716/107737293-74865b80-6d47-11eb-98ad-7b8af764f0c8.png)
