### ISSUE TITLE
Study how to build chat service with spring

### ISSUE THREAD

**Issue by bluewink** [WinterSpringProject/PROJECT-GLFP#29]
웹소켓, stomp, sockJS 등 스프링에서 채팅 서비스를 구현하는데 필요한 것들을 공부합시다.

아래 레퍼런스를 추가해 주세요!

## References
- https://rmcodestar.github.io/websocket/2019/02/11/spring-websocket/
- https://supawer0728.github.io/2018/03/30/spring-websocket/
- https://blog.naver.com/PostView.nhn?blogId=scw0531&logNo=221097188275&proxyReferer=http:%2F%2F221.163.210.133%2F (STOMP 관련 포스팅)
- https://www.youtube.com/watch?v=Ax0fDdlBev8 (spring web-socket 활용방법 소개 영상)
- https://daddyprogrammer.org/post/4691/spring-websocket-chatting-server-stomp-server/
- https://hwiveloper.dev/2019/01/10/spring-boot-stomp-websocket/

**Comment by Ohhong** [comment]
이런 스터디 내용들이 wiki로 정리되면 좋을것 같아요~

**Comment by simsulison** [comment]
https://github.com/WinterSpringProject/PROJECT-GLFP/wiki/Chat
