### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by k0k0k02** [WinterSpringProject/PROJECT-GLFP#3]
### 데이터베이스 설계 순서

1. 데이터 요구 사항 분석
2. 개념 스키마 설계 (E-R 다이어그램 작성)
3. 논리 스키마 설계
4. 내부 스키마 (물리적) 설계
5. 구현

https://advenoh.tistory.com/31
DB 설계 관련 정보 링크입니다.

**Comment by k0k0k02** [comment]
![image](https://user-images.githubusercontent.com/76993693/106724686-da8a2900-664b-11eb-8b7a-5590a0e4f331.png)
게시판 및 유저 정보 저장을 위한 데이터 베이스 ERD입니다.

1. 사용자 테이블
: 사용자의 정보(ID, PW, 성별, 이름)을 저장하는 테이블입니다.

2. 게시판 테이블
: 게시판의 정보를 저장하는 테이블입니다.
글 번호, 글 제목, 등록 시간, 매칭 상태를 저장하고 있으며, 사용자의 ID 키를 통해 글쓴이의 정보를 가져올 수 있습니다.

3. 매칭 조건 테이블
: 사용자를 매칭할 때 선택하는 매칭 조건을 저장하는 테이블입니다.
* 해당 정보가 필요하지 않은 경우 Null을 저장합니다.
(1) 게임 종류: 롤, 오버워치 등 매칭을 원하는 게임의 종류
(2) 티어: 선택한 게임 내의 티어 *
(3) 맵: 선택한 게임에서 원하는 맵 *
(4) 게임 모드: 일반 게임, 경쟁전 등 게임 모드
(5) 포지션: 게임 내의 사용자의 포지션에 대한 정보 *
(6) 연령대: 사용자의 연령대
(7) 성별: 사용자의 성별
(8) 음성 채팅 여부: 디스코드 등의 음성 채팅의 사용 여부 (0: 사용x, 1: 사용)
(9) 게임 서버: 선택한 게임 내의 서버 *



또한 채팅 서버에 대한 정보 저장을 위한 데이터 베이스로 Redis라는 비관계형 데이터 베이스를 사용할 예정입니다.
Redis는 '해당 채널을 구독한 사용자에게만 메시지를 발/수신하는' pub/sub (발행/구독) 모델을 지원하고 있습니다.
Redis의 데이터 베이스 구조의 경우 차후 개발 해 나가면서 추가하겠습니다.

**Comment by simsulison** [comment]
각 테이블에 대한 간단한 설명도 부탁드려요!

**Comment by k0k0k02** [comment]
![image](https://user-images.githubusercontent.com/76993693/107118445-6a3a0c80-68c4-11eb-90a1-5448bed8077f.png)


* 기존 매칭 조건 테이블은 추가 기능 구현시 사용

**Comment by bluewink** [comment]
## Database Server specification
- AWS EC2 Instance
- Ubuntu Server 20.04 LTS (HVM)
- t2.micro (- ECU, 1 vCPUs, 2.5 GHz, -, 1 GiB 메모리, EBS 전용)
- public IPv4 address : 3.15.215.122
- port number : 3306

**Comment by simsulison** [comment]
https://github.com/WinterSpringProject/PROJECT-GLFP/wiki/Database
