### ISSUE TITLE
Spring security

### ISSUE THREAD

**Issue by bluewink** [WinterSpringProject/PROJECT-GLFP#30]
spring security를 활용해 회원가입/로그인/권한 문제를 해결합시다

## References
- https://galid1.tistory.com/700?category=791456
- https://victorydntmd.tistory.com/328
- https://kouzie.github.io/spring/Spring-Boot-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B6%80%ED%8A%B8-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0/#%EB%A1%9C%EA%B7%B8%EC%9D%B8-%ED%9B%84-%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%9D%B4%EB%8F%99

**Comment by bluewink** [comment]
## 작업완료
- security 관련 skeleton code

## TO-DO
- 비밀번호 암호화
- JWT 토큰 관리 -> spring security에서 어떻게 생성/조회 하는지...?
- 회원가입/로그인 로직을 DB와 연결 -> 첫번째 Reference 참조

## Notice
현재 localhost에 접속하면 다음과 같은 로그인 화면이 나옴. 
로그인하기 전까지는 다른 url로 넘어갈 수 없음.
![image](https://user-images.githubusercontent.com/59544716/108600704-fdeafd00-73db-11eb-9dc9-761368b005b5.png)

username: user를 넣고, password에 아래와 같이 console 창에 뜨는 비밀번호를 입력하면 됨. 
![image](https://user-images.githubusercontent.com/59544716/108600693-f0357780-73db-11eb-8ec3-0e57295ac0ca.png)
관련 내용은 첫번째 reference를 참조 바람.

**Comment by simsulison** [comment]
Security principal 객체를 사용한 login 기능 구현 reference
https://codevang.tistory.com/273
