### ISSUE TITLE
Ready for software distribution

### ISSUE THREAD

**Issue by simsulison** [WinterSpringProject/PROJECT-GLFP#32]
# 배포를 위한 준비

- 프론트 엔드와 연동을 위해 클라우드 서버를 활용해 백엔드 서버를 올린다.
- 관련 내용에 대해 조사하여 Reference 추가 후, 조사 완료 시 wiki에 정리하여 issue closing할 것.

# Reference
https://fors.tistory.com/572

**Comment by simsulison** [comment]
채팅 기능까지 개발 후 배포하겠습니다.

**Comment by bluewink** [comment]
문제가 생겼습니당...
ec2에 저희 database를 올려놓았었는데 제가 key 파일을 삭제해버렸어요,,,

그래도 다행인점은 어차피 ec2 server와 db server를 따로 두는 것이 좋다고 하네요... 그래서 제안드리는 점이,
여기서 RDS로 넘어가는 것이 어떨까요..?
EC2 server 1개 + RDS 1개 로 운영하는 것을 제안드립니당...

## Reference
- 게시판 프로그램 배포하는 예제 https://victorydntmd.tistory.com/338
- RDS 생성 + EC2 서버와 연결 https://twofootdog.tistory.com/41

**Comment by k0k0k02** [comment]
네네 오히려 좋네요!ㅎㅎ
올려주신 블로그가 잘 나와있어서 이따가 같이 해보면 좋을 것 같습니다~

**Comment by simsulison** [comment]
넵 사실 DB서버를 만들어보는 경험에 의의가 있었던지라 RDS로 돌려도 상관없을 것 같습니다!
