### ISSUE TITLE
Search Service implementation

### ISSUE THREAD

**Issue by k0k0k02** [WinterSpringProject/PROJECT-GLFP#39]
게시판 내 검색 기능을 구현한다.

**Comment by simsulison** [comment]
### Reference
- https://semtax.tistory.com/78
- https://velog.io/@max9106/Spring-Boot-JPA-MySQL-검색기능
- https://www.baeldung.com/spring-jpa-like-queries (JPA like query 정리)
- https://victorydntmd.tistory.com/333

**Comment by k0k0k02** [comment]
게시판의 전반적인 정보도 있고, 따라가면 생각보다 쉽게 구현할 수 있을 것 같네요
서버 연동되기 전에 미리 구현해봐도 괜찮을 것 같습니다!

**Comment by simsulison** [comment]
GLFP는 현재 한 개의 게시판이 아닌 각 게임별 여러 개의 게시판을 보유하고 있기 때문에 JPQL을 사용하거나, pagenation을 통해 제한된 개수만 검색할 수 있게 구현해야 할 것 같습니다.

### Reference
https://ict-nroo.tistory.com/117
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example
