### ISSUE TITLE
General WS communication vs STOMP

### ISSUE THREAD

**Issue by bluewink** [WinterSpringProject/PROJECT-GLFP#43]
### (3) 기본적으로 자바가 제공하는 웹 소켓 통신이 아닌 STOMP를 사용하는 이유?

무엇인지 공부해 봅시다.

## References
- sockJS, STOMP 란 무엇인지 & spring에서의 활용 https://velog.io/@koseungbin/WebSocket

**Comment by simsulison** [comment]
(3)에 대한 reference입니다.
https://daddyprogrammer.org/post/4691/spring-websocket-chatting-server-stomp-server/

**Comment by bluewink** [comment]
## (0) WebSocket이란?
Transport layer protocol 중 하나로 웹버전의 TCP 혹은 웹버전의 Socket
### 왜 사용할까?
#### HTTP의 문제점
HTTP는 request/response기반의 Stateless protocol -> 클라이언트가 request를 보내야만 서버가 response하는 일방향 통신. -> 서버 쪽 데이터가 업데이트 되더라도 클라이언트에서 refresh하지 않으면 데이터가 업데이트되지 않음. -> 실시간 어플리케이션에 부적합.
#### 그렇다면 WebSocket은?
WebSocket은 Stateful protocol이기 때문에 클라이언트와 한 번 연결이 되면 같은 라인을 사용해서 **양방향으로** 통신.
또한 Web Socket은 일반적인 socket과 달리 HTTP와 같은 포트(80)을 사용하기에 기존 웹어플리케이션의 방화벽을 재설정하지 않아도 된다는 장점이 있다.
접속까지는 HTTP protocol을 사용하고 이후에는 자체적인 websocket protocol을 사용.

## (1) SockJS 란?
WebSocket과 유사한 객체를 제공하는 브라우저 JavaScript 라이브러리
WebSocket은 HTML5부터 표준에 들어갔지만 이를 제공하지 않는 브라우저가 존재한다. 이 때 SockJS는 브라우저와 관계없이 WebSocket 기능을 사용할 수 있게 해준다.
## (2) STOMP란?
Simple/Stream Text Oriented Messaging Protocol (문자 기반 메시징 프로토콜)
메시징 전송을 효율적으로 하기 위한 프로토콜
```
COMMAND
header1:value1
header2:value2

BODY^@
```

COMMAND 목록
```
CONNECT
SEND
SUBSCRIBE
UNSUBSCRIBE
DISCONNECT
...
```
FRAME 예시
```
SEND
destination:/queue/a
receipt:message-12345

hello queue a^@
```
## (3) 왜 STOMP를 추가적으로 사용할까?
- WebSocket만을 이용해 채팅을 구현하면 해당 메시지가 어떤 요청인지, 어떻게 처리해야 하는지 구현이 까다로움. -> STOMP는 PUB/SUB 구조로 되어있어 메시지를 발송하고 메시지를 받아서 처리하는 부분이 확실히 구분되어 있음.
- WebSocket은 1:1 통신에 적합하고 1:N 채팅 구현은 쉽지 않음 -> STOMP를 이용하면 1:N 채팅을 편리하게 구현 가능
- STOMP 헤더를 이용하면 인증 처리 구현이 용이함.
