### ISSUE TITLE
Form data vs Common request

### ISSUE THREAD

**Issue by simsulison** [WinterSpringProject/PROJECT-GLFP#44]
Client단에서 Form data요청을 보낼 때와 일반적인 요청을 보낼 때의 차이에 대하여 공부해보겠습니다.

**Comment by simsulison** [comment]
Reference를 추가합니다.
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestBody.html
- http://wonwoo.ml/index.php/post/1834
- https://enterkey.tistory.com/276
- https://www.inflearn.com/questions/15242

**Comment by k0k0k02** [comment]
### [RequestBody 어노테이션의 필요성 및 Message Converter]

요청된 본문의 데이터가 form data가 아닌 경우 spring 내에서는 어떤 데이터를 요청하는 것인지 몰라 바인딩을 하지 못하는데, (Form data인 경우는 가능)
이러한 form data 이외의 요청에 대한 바인딩을 가능하게 하기 위해 `@RequestBody` 어노테이션을 사용합니다.
(주로 XML, JSON)

`@RequestBody` 어노테이션을 명시하면 스프링은 `Message Converter`를 사용하여 HTTP요청 혹은 응답을 메시지로 변환시켜주는데, 스프링은 자체적으로 파라미터 및 return 타입에 맞는 `Message Converter`를 선택합니다.

Spring에는 디폴트로 아래 4가지의 Message Converter가 등록되어 있으며, `AnnotationMethodHandlerAdapter`를 통해 추가할 수 있습니다.

1. ByteArrayHttpMessageConverter : 요청을 Byte배열로 받을 수 있게 함.

2. StringHttpMessageConverter : HTTP 본문을 String으로 가져올 수 있게 함.

3. FormHttpMessageConverter : 정의된 Form data를 주고받을 때 사용.

4. SourceHttpMessageConvreter : XML문서를 Source 타입의 오브젝트로 변환하고 싶을 때 사용.

>https://joont92.github.io/spring/MessageConverter/
