### ISSUE TITLE
Resolve ec2 server down problem

### ISSUE THREAD

**Issue by k0k0k02** [WinterSpringProject/PROJECT-GLFP#45]
EC2와 연동하여 스프링 부트를 실행하였을 때 서버가 다운이 되는 문제를 해결합시다.

**Comment by k0k0k02** [comment]
고려할만한 점
1. Swap Memory 활용
2. 스웨거 끄기

**Comment by bluewink** [comment]
정재님 조언대로 
swap memory를 할당해서 문제 해결 했습니다.
관련해서 제 개인 블로그에 정리해두었으니 참고하시기 바랍니당!
### Reference
https://flowingmooon.tistory.com/22
