### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by bluewink** [WinterSpringProject/PROJECT-GLFP#46]
프론트엔드와 연동을 시도했으나 CORS error가 떴습니다...
CORS error 를 해결해 봅시다.

## Reference
- https://ithub.tistory.com/63 => controller에 ```@CrossOrigin(origins = "*")``` 을 추가해보았으나 해결되지 않음..

**Comment by simsulison** [comment]
### Cors Error에 대한 Reference
https://coding-groot.tistory.com/91
https://developer.mozilla.org/ko/docs/Web/HTTP/CORS
Spring boot에서 시도해 볼만한 것
https://siyoon210.tistory.com/154
Proxy를 이용하는 방법
https://shinsunyoung.tistory.com/86

**Comment by simsulison** [comment]
https://github.com/WinterSpringProject/PROJECT-GLFP/wiki/Security
 설정을 하였는데도 안된 동일한 에러가 발생하였었는데, front단에서 axios를 이용하여 요청을 보낼 때 URL scheme을 명시하지 않을 경우 SOP에 따라 Same origin으로 판단하지 않아서 계속해서 오류가 발생했었습니다.
