### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by bluewink** [WinterSpringProject/PROJECT-GLFP#5]
## 구현해야할 화면 목록
- 메인화면(랜딩페이지) (상빈_완료)
- 게임별 공동 채팅방 (상빈_완료)
- 1:1 채팅방 (상빈_완료)
- 게임 친구 구하는 게시판 (상빈_완료)
- 회원가입
- 로그인
- 1:1 채팅 요청
- 1:1 채팅 요청 내역 확인(마이페이지)

---
## Reference
- https://discord.com/
- http://dami.chat/
- https://moduo.kr/

**Comment by bluewink** [comment]
[GLFP_wireframe_1.pdf](https://github.com/WinterSpringProject/PROJECT-GLFP/files/5902894/GLFP_wireframe_1.pdf)

**Comment by bluewink** [comment]
[GLFP_wireframe_1.pdf](https://github.com/WinterSpringProject/PROJECT-GLFP/files/5902900/GLFP_wireframe_1.pdf)
어떻게 바로 볼 수 있게 올리는지 몰라서 일단 파일만 올려두었습니다 ㅠㅠ
다른 분들도 확인해보시고 피드백 부탁드립니다~

@Jin-s-work 
만약 더 추가해야 하는 화면이 있다고 생각하시면 위에 목록에 추가해주시면 될 것 같아요!
남은 페이지 작업 부탁드립니다! 🙏

**Comment by Jin-s-work** [comment]
메인화면(랜딩페이지) (상빈_완료)
게임별 공동 채팅방 (상빈_완료)
1:1 채팅방 (상빈_완료)
게임 친구 구하는 게시판 (상빈_완료)
회원가입(상우_완료)
로그인(상우_완료)
1:1 채팅 요청(상우_완료)
1:1 채팅 요청 내역 확인(마이페이지)(상우_완료)
+ 마이페이지(상우_완료)

**Comment by Jin-s-work** [comment]
[New Project.pdf](https://github.com/WinterSpringProject/PROJECT-GLFP/files/5909115/New.Project.pdf)

구현 해야 하는 것들 몇개 더 추가하고 수정해보았습니다!
더 필요해 보이는 페이지들 생각나면 오늘 중으로 더 추가해보도록 하겠습니다
무언가 부족해보인다 싶으면 제가 다시 고쳐볼테니 편하게 의견 제시부탁드려요~

**Comment by Jin-s-work** [comment]
[New Project (RE).pdf](https://github.com/WinterSpringProject/PROJECT-GLFP/files/5909530/New.Project.RE.pdf)

요청하신 부분 수정해보았습니니다.
더 필요한게 있으면 말해주세요!

**Comment by Jin-s-work** [comment]
[New Project_RE.pdf](https://github.com/WinterSpringProject/PROJECT-GLFP/files/5909552/New.Project_RE.pdf)

요청해주신 부분 수정해보았습니다.
더 필요한 부분이 있으면 의견 제시 부탁드려요!

**Comment by Ohhong** [comment]
이런 와이어 프레임은 FE repo에서 설계 되는게 더좋아보이네요~

**Comment by Jin-s-work** [comment]
@Ohhong 조언 감사합니다!
혹시 이런 issue들을 다른 repo로 옮기는 방법이 있을까요?
아니면 다시 만들어야 할까요?

**Comment by Ohhong** [comment]
아하 다시 생성하셔도 좋을 것 같고 얼추 정리 되었다면 wiki를 통해서 정리하셔도 될것 같습니다.

**Comment by Jin-s-work** [comment]
아 그렇군요 의견 주셔서 감사합니다!
