### ISSUE TITLE
Readme Documentation

### ISSUE THREAD

**Issue by simsulison** [WinterSpringProject/PROJECT-GLFP#6]
# Readme 파일 작성

- 간단한 프로젝트 logo 제작
- 기술 스택 
- 프로젝트 설명

**Comment by simsulison** [comment]
간단한 프로젝트 로고는 제작 완료하였습니다. 기술 스택은 이미지로 할지, 글로 할지 선택하여 제안해주시면 감사하겠습니다.
개인적으로 눈에 띄게 이미지로 하는 것이 좋다고 생각합니다.
프로젝트 설명은 저희 프로젝트를 한 줄로 표현할 수 있는 짧은 글 정도로 작성할 예정입니다.

**Comment by Jin-s-work** [comment]
저도 한눈에 들어오게 이미지로 하는 것이 좋을 거 같다고 생각합니다.
