### ISSUE TITLE
Make a Skeleton Code

### ISSUE THREAD

**Issue by k0k0k02** [WinterSpringProject/PROJECT-GLFP#9]
프로젝트의 뼈대가 되는 기본 파일을 생성한다.

**Comment by simsulison** [comment]
Dependency List : Spring Web, Spring Data JPA, Lombok, MariaDB driver
말 그대로 기초 파일이므로, DB 연동이나 다른 기능적인 부분에 대한 Code는 다른 issue에서 다뤄질 예정입니다.
